# PREPARACION DE DATOS

# Preparación de datos -  Empleados



1. Integración de los datos

2. Eliminar variables irrelevantes y redundantes

3. Descripción estadística de los datos

4. Limpieza de datos

5. Análisis de correlaciones

6. Balanceo de datos

7. Transformación de tipo de variable según el método de ML

8. Guardar los datos preparados


In [1]:
#IMPORTAR LIBRERIAS
import pandas as pd #manipulacion de datos
import numpy as np #matrices y vectores
import matplotlib.pyplot as plt #grafica

In [2]:
data = pd.read_csv("drugs.csv", encoding='utf-8')
data.head()

ID  EDAD SEXO PRESIÓN SANGUÍNEA COLESTEROL     SODIO   POTASIO MEDICAMENTO
0   1    23    F              HIGH       HIGH  0.792535  0.031258       drugY
1   2    47    M               LOW       HIGH  0.739309  0.056468       drugC
2   3    47    M               LOW       HIGH  0.697269  0.068944       drugC
3   4    28    F            NORMAL       HIGH  0.563682  0.072289       drugX
4   5    61    F               LOW       HIGH  0.559294  0.030998       drugY

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   ID                 200 non-null    int64  
 1   EDAD               200 non-null    int64  
 2   SEXO               200 non-null    object 
 3   PRESIÓN SANGUÍNEA  200 non-null    object 
 4   COLESTEROL         200 non-null    object 
 5   SODIO              200 non-null    float64
 6   POTASIO            200 non-null    float64
 7   MEDICAMENTO        200 non-null    object 
dtypes: float64(2), int64(2), object(4)
memory usage: 12.6+ KB


In [4]:
# Renombramiento de columnas

data = data.rename(columns={'ID':'Id', 'EDAD':'Edad', 'SEXO':'Sexo', 'PRESIÓN SANGUÍNEA':'PresionSanguinea',
                           'COLESTEROL':'Colesterol', 'SODIO':'Sodio', 'POTASIO':'Potasio', 'MEDICAMENTO':'Medicamento'})

data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Id                200 non-null    int64  
 1   Edad              200 non-null    int64  
 2   Sexo              200 non-null    object 
 3   PresionSanguinea  200 non-null    object 
 4   Colesterol        200 non-null    object 
 5   Sodio             200 non-null    float64
 6   Potasio           200 non-null    float64
 7   Medicamento       200 non-null    object 
dtypes: float64(2), int64(2), object(4)
memory usage: 12.6+ KB


In [21]:
data['Sexo']=data['Sexo'].astype('category')
data['PresionSanguinea']=data['PresionSanguinea'].astype('category')
data['Colesterol']=data['Colesterol'].astype('category')
data['Medicamento']=data['Medicamento'].astype('category')


data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 197 entries, 0 to 199
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype   
---  ------            --------------  -----   
 0   Edad              197 non-null    float64 
 1   Sexo              197 non-null    category
 2   PresionSanguinea  197 non-null    category
 3   Colesterol        197 non-null    category
 4   Sodio             197 non-null    float64 
 5   Potasio           197 non-null    float64 
 6   Medicamento       197 non-null    category
dtypes: category(4), float64(3)
memory usage: 7.5 KB


In [6]:
#Revisamos si tenemos ID repetidos

ids = data['Id'].value_counts()

ids[ids > 1]
# No hay Ids repetidos.

Series([], Name: Id, dtype: int64)

ELIMINANDO VARIABLES IRRELEVANTES O REDUNDANTES

In [7]:
# Variables irrelevantes para el proceso de minería

data = data.drop('Id',axis=1) #Eliminamos el ID por ser irrelevante, axis=1 indica que es una columna

data.head()

Edad Sexo PresionSanguinea Colesterol     Sodio   Potasio Medicamento
0    23    F             HIGH       HIGH  0.792535  0.031258       drugY
1    47    M              LOW       HIGH  0.739309  0.056468       drugC
2    47    M              LOW       HIGH  0.697269  0.068944       drugC
3    28    F           NORMAL       HIGH  0.563682  0.072289       drugX
4    61    F              LOW       HIGH  0.559294  0.030998       drugY

DESCRIPCIÓN ESTADÍSTICA

In [8]:
data.describe()

Edad       Sodio     Potasio
count  200.000000  200.000000  200.000000
mean    45.585000    0.688606    0.098808
std     19.460378    0.161127    0.703927
min     15.000000   -0.848948   -0.076100
25%     31.750000    0.582655    0.034697
50%     45.000000    0.721338    0.049187
75%     58.250000    0.796636    0.065663
max    154.000000    0.896056   10.000000

In [9]:
edad_unique, counts = np.unique(data['Edad'], return_counts=True)
print(edad_unique)
print(counts)

[ 15  16  17  18  19  20  21  22  23  24  25  26  28  29  30  31  32  33
  34  35  36  37  38  39  40  41  42  43  45  46  47  48  49  50  51  52
  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70
  72  73  74 145 154]
[3 3 1 3 2 4 1 4 6 4 1 4 7 2 1 4 6 1 4 3 4 5 3 6 3 4 4 4 4 2 8 2 7 5 4 2 3
 1 2 4 4 5 3 5 4 2 1 3 4 2 4 4 3 3 4 2 4 1 1]


In [10]:
# Cleaning atypical ages
data.Edad[data['Edad']>120] = np.nan

edad_unique, counts = np.unique(data['Edad'], return_counts=True)
print(edad_unique)
print(counts)

[15. 16. 17. 18. 19. 20. 21. 22. 23. 24. 25. 26. 28. 29. 30. 31. 32. 33.
 34. 35. 36. 37. 38. 39. 40. 41. 42. 43. 45. 46. 47. 48. 49. 50. 51. 52.
 53. 54. 55. 56. 57. 58. 59. 60. 61. 62. 63. 64. 65. 66. 67. 68. 69. 70.
 72. 73. 74. nan nan]
[3 3 1 3 2 4 1 4 6 4 1 4 7 2 1 4 6 1 4 3 4 5 3 6 3 4 4 4 4 2 8 2 7 5 4 2 3
 1 2 4 4 5 3 5 4 2 1 3 4 2 4 4 3 3 4 2 4 1 1]


<ipython-input-10-ba2d73c23da6>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.Edad[data['Edad']>120] = np.nan


In [11]:
data = data.dropna()

In [12]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 198 entries, 0 to 199
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype   
---  ------            --------------  -----   
 0   Edad              198 non-null    float64 
 1   Sexo              198 non-null    category
 2   PresionSanguinea  198 non-null    category
 3   Colesterol        198 non-null    category
 4   Sodio             198 non-null    float64 
 5   Potasio           198 non-null    float64 
 6   Medicamento       198 non-null    category
dtypes: category(4), float64(3)
memory usage: 7.6 KB


In [13]:
sexo_unique, counts = np.unique(data['Sexo'], return_counts=True)
print(sexo_unique)
print(counts)

['F' 'M' 'Mujer']
[ 95 102   1]


In [14]:
# Replacing column values
data['Sexo'].replace({'Mujer':'M'}, inplace=True)
data['Sexo'].unique()

['F', 'M']
Categories (2, object): ['F', 'M']

In [15]:
presion_unique, counts = np.unique(data['PresionSanguinea'], return_counts=True)
print(presion_unique)
print(counts)

['HIGH' 'LOW' 'NORMAL' 'Null']
[75 63 59  1]


In [16]:
data['PresionSanguinea'].replace({'Null': np.nan}, inplace=True)
data = data.dropna()
data['PresionSanguinea'].unique()

['HIGH', 'LOW', 'NORMAL']
Categories (3, object): ['HIGH', 'LOW', 'NORMAL']

In [17]:
colesterol_unique, counts = np.unique(data['Colesterol'], return_counts=True)
print(colesterol_unique)
print(counts)

['HIGH' 'NORMAL' 'hig']
[101  95   1]


In [18]:
data['Colesterol'].replace({'hig': 'HIGH'}, inplace=True)
data['Colesterol'].unique()

['HIGH', 'NORMAL']
Categories (2, object): ['HIGH', 'NORMAL']

In [19]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 197 entries, 0 to 199
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype   
---  ------            --------------  -----   
 0   Edad              197 non-null    float64 
 1   Sexo              197 non-null    category
 2   PresionSanguinea  197 non-null    category
 3   Colesterol        197 non-null    category
 4   Sodio             197 non-null    float64 
 5   Potasio           197 non-null    float64 
 6   Medicamento       197 non-null    category
dtypes: category(4), float64(3)
memory usage: 7.5 KB


In [20]:
sodio_unique, counts = np.unique(data['Sodio'], return_counts=True)
print(sodio_unique)
print(counts)

[0.500169 0.501956 0.50482  0.504995 0.509181 0.510473 0.512517 0.5126
 0.516973 0.517515 0.518285 0.522891 0.523623 0.526102 0.526226 0.526672
 0.526835 0.52765  0.52975  0.532632 0.533228 0.536324 0.536746 0.538183
 0.538856 0.539774 0.543355 0.547347 0.547821 0.549375 0.549945 0.551967
 0.553567 0.554182 0.556833 0.557133 0.55906  0.559171 0.559294 0.560854
 0.561019 0.563217 0.56332  0.563682 0.564811 0.575058 0.578002 0.581591
 0.58301  0.584179 0.589493 0.593596 0.596099 0.598753 0.601915 0.602557
 0.604973 0.606933 0.609566 0.611333 0.613261 0.616117 0.616692 0.618603
 0.625272 0.625889 0.626527 0.627866 0.63126  0.635551 0.635762 0.637231
 0.639888 0.640455 0.64236  0.643455 0.644936 0.645515 0.648646 0.649096
 0.655222 0.656292 0.656371 0.658397 0.658606 0.663146 0.667775 0.676901
 0.678646 0.683503 0.685143 0.694689 0.695183 0.697052 0.697269 0.71486
 0.715337 0.721257 0.72142  0.722286 0.724375 0.724422 0.725424 0.726677
 0.730854 0.731091 0.73154  0.733842 0.734119 0.739309