# NumPy

NumPy es una librería que proporciona una estructura de datos de matriz que tiene algunos beneficios sobre las listas regulares de Python

### ¿Qué es NumPy array?

es un potente objeto de matriz N-dimensional que tiene forma de filas y columnas, en la que tenemos varios elementos que están almacenados en sus respectivas ubicaciones de memoria.

In [1]:
# importando
import numpy as np

Matriz unidimensional

In [2]:
a = np.array([1, 2, 3])
print('1D array:')
print(a)

1D array:
[1 2 3]


Matriz bidimensional

In [3]:
b = np.array([(1, 2, 3), (4, 5, 6)])
print('2D array:')
print(b)

2D array:
[[1 2 3]
 [4 5 6]]


Matriz de unos - 3 filas 4 columnas

In [4]:
unos = np.ones((3,4))
print(unos)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


Crear una matriz de ceros - 3 filas 4 columnas

In [5]:
ceros = np.zeros((3,4))
print(ceros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


Crear una matriz con valores aleatorios

In [6]:
aleatorios = np.random.random((2,2))
print(aleatorios)

[[0.62963746 0.05062415]
 [0.37959089 0.14855448]]


Crear una matriz vacía

In [7]:
vacia = np.empty((3,2))
print(vacia)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


Crear una matriz con un solo valor

In [8]:
full = np.full((2,2),8)
print(full)

[[8 8]
 [8 8]]


Crear una matriz con valores espaciados uniformemente

In [9]:
espacio1 = np.arange(0,30,5) # Se especifica que la matriz empieza en 0. Los pasos son de 5. Hasta 30 exclusivo.
print(espacio1)

espacio2 = np.linspace(0,2,5) # Matriz con 5 valores que se encuentren entre 0 y 2.
print(espacio2)

[ 0  5 10 15 20 25]
[0.  0.5 1.  1.5 2. ]


Crear una matriz identidad

In [10]:
identidad1 = np.eye(4,4)
print(identidad1)

identidad2 = np.identity(4)
print(identidad2)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Conocer las dimensiones de una matriz

In [14]:
a = np.array([(1,2,3), (4,5,6)])
print(a.ndim)

2


Conocer el tipo de datos

In [15]:
a = np.array([(1,2,3)])
print(a.dtype)

int32


Conocer el tamaño y la forma de la matriz

In [16]:
a = np.array([(1,2,3,4,5,6)])
print(a.size)
print(a.shape)

6
(1, 6)


Cambio de forma de una matriz

In [17]:
a = np.array([(8,9,10), (11,12,13)])
print(a)
a = a.reshape(3,2)
print(a)

[[ 8  9 10]
 [11 12 13]]
[[ 8  9]
 [10 11]
 [12 13]]


Extraer un solo valor de la matriz - el valor ubicado en la fila 0 columna 2

In [18]:
a = np.array([(1,2,3,4), (3,4,5,6)])
print(a[0,2])

3


Extraer los valores de todas las filas ubicados en la columna 3

In [19]:
a = np.array([(1,2,3,4), (3,4,5,6)])
print(a[0:,2])

[3 5]


Encontrar el mínimo, máximo y la suma

In [20]:
a = np.array([2,4,8])
print(a.min())
print(a.max())
print(a.sum())

2
8
14


Calcular la raíz cuadrada y la desviación estándar de una matriz

In [21]:
a = np.array([(1,2,3), (3,4,5,)])
print(np.sqrt(a))
print(np.std(a))

[[1.         1.41421356 1.73205081]
 [1.73205081 2.         2.23606798]]
1.2909944487358056


Calcular suma, resta, multiplicación y división entre dos semanas

In [22]:
x = np.array([(1,2,3),(3,4,5)])
y = np.array([(1,2,3),(3,4,5)])
print(x+y)
print(x-y)
print(x*y)
print(x/y)

[[ 2  4  6]
 [ 6  8 10]]
[[0 0 0]
 [0 0 0]]
[[ 1  4  9]
 [ 9 16 25]]
[[1. 1. 1.]
 [1. 1. 1.]]
