# NumPy

NumPy es una librería que proporciona una estructura de datos de matriz que tiene algunos beneficios sobre las listas regulares de Python

### ¿Qué es NumPy array?

es un potente objeto de matriz N-dimensional que tiene forma de filas y columnas, en la que tenemos varios elementos que están almacenados en sus respectivas ubicaciones de memoria.

In [2]:
# importando
import numpy as np

Matriz unidimensional

In [3]:
a = np.array([1, 2, 3])
print('1D array:')
print(a)

1D array:
[1 2 3]


Matriz bidimensional

In [13]:
b = np.array([(1, 2, 3), (4, 5, 6)])
print('2D array:')
print(b)

2D array:
[[1 2 3]
 [4 5 6]]


Matriz de unos - 3 filas 4 columnas

In [14]:
unos = np.ones((3,4))
print(unos)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


Crear una matriz de ceros - 3 filas 4 columnas

In [15]:
ceros = np.zeros((3,4))
print(ceros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


Crear una matriz con valores aleatorios

In [16]:
aleatorios = np.random.random((2,2))
print(aleatorios)

[[0.33332021 0.58013255]
 [0.91843469 0.74854683]]


Crear una matriz vacía

In [18]:
vacia = np.empty((3,2))
print(vacia)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


Crear una matriz con un solo valor

In [19]:
full = np.full((2,2),8)
print(full)

[[8 8]
 [8 8]]


Crear una matriz con valores espaciados uniformemente

In [21]:
espacio1 = np.arange(0,30,5) # Se especifica que la matriz empieza en 0. Los pasos son de 5. Hasta 30 exclusivo.
print(espacio1)

espacio2 = np.linspace(0,2,5) # Matriz con 5 valores que se encuentren entre 0 y 2.
print(espacio2)

[ 0  5 10 15 20 25]
[0.  0.5 1.  1.5 2. ]


Crear una matriz identidad

In [22]:
identidad1 = np.eye(4,4)
print(identidad1)

identidad2 = np.identity(4)
print(identidad2)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
a = 